#!/usr/bin/env bash

[ -z $1 ] && echo "Please specify project name" && exit 1

PROJECT=$1

# logs
docker build -t marm-data-log-${PROJECT} --build-arg PROJECT_NAME=${PROJECT} ./data/log/

# cron
docker build -t marm-cron-${PROJECT} --build-arg PROJECT_NAME=${PROJECT} ./cron

# logrotate
docker build -t marm-logrotate-${PROJECT} --build-arg PROJECT_NAME=${PROJECT} ./logrotate