#!/usr/bin/env bash

[ -z $1 ] && echo "Please specify env" && exit 1

ENV=$1

# data

docker build -t marm-data-printform-${ENV} --build-arg SOURCE_NAME=printform ./data/www/

# yarg

docker build -t marm-yarg ./yarg

# server

docker build -t marm-server-printform --build-arg CONF_NAME=printform.conf ./server/
