#!/usr/bin/env bash

# Образы для разворачивания проекта

[ -z $1 ] && echo "Please specify project name" && exit 1
[ -z $2 ] && echo "Please specify box version" && exit 1

# Версия сервера
PROJECT=$1
VERSION=$2

REGISTRY=172.29.134.38:5000

docker pull ${REGISTRY}/marm-data-box-${PROJECT}:${VERSION}
docker pull ${REGISTRY}/marm-data-integrator-${PROJECT}:${VERSION}
docker pull ${REGISTRY}/marm-data-log-${PROJECT}
docker pull ${REGISTRY}/marm-cron-${PROJECT}
docker pull ${REGISTRY}/marm-logrotate-${PROJECT}


docker tag ${REGISTRY}/marm-data-box-${PROJECT}:${VERSION} marm-data-box-${PROJECT}:${VERSION}
docker tag ${REGISTRY}/marm-data-integrator-${PROJECT}:${VERSION} marm-data-integrator-${PROJECT}:${VERSION}
docker tag ${REGISTRY}/marm-data-log-${PROJECT} marm-data-log-${PROJECT}
docker tag ${REGISTRY}/marm-cron-${PROJECT} marm-cron-${PROJECT}
docker tag ${REGISTRY}/marm-logrotate-${PROJECT} marm-logrotate-${PROJECT}

