#!/usr/bin/env bash

# Образы для разворачивания проекта

[ -z $1 ] && echo "Please specify project name" && exit 1
[ -z $2 ] && echo "Please specify box version" && exit 1
[ -z $3 ] && echo "Please specify env" && exit 1

# Версия сервера
PROJECT=$1
VERSION=$2
ENV=$3

REGISTRY=172.29.134.38:5000

docker pull ${REGISTRY}/marm-data-box-${PROJECT}-${ENV}:${VERSION}
docker pull ${REGISTRY}/marm-data-integrator-${PROJECT}-${ENV}:${VERSION}
docker pull ${REGISTRY}/marm-data-log-${PROJECT}
docker pull ${REGISTRY}/marm-cron-${PROJECT}-${ENV}
docker pull ${REGISTRY}/marm-logrotate-${PROJECT}-${ENV}


docker tag ${REGISTRY}/marm-data-box-${PROJECT}-${ENV}:${VERSION} marm-data-box-${PROJECT}-${ENV}:${VERSION}
docker tag ${REGISTRY}/marm-data-integrator-${PROJECT}-${ENV}:${VERSION} marm-data-integrator-${PROJECT}-${ENV}:${VERSION}
docker tag ${REGISTRY}/marm-data-log-${PROJECT} marm-data-log-${PROJECT}
docker tag ${REGISTRY}/marm-cron-${PROJECT}-${ENV} marm-cron-${PROJECT}-${ENV}
docker tag ${REGISTRY}/marm-logrotate-${PROJECT}-${ENV} marm-logrotate-${PROJECT}-${ENV}

