#!/usr/bin/env bash

REGISTRY=172.29.134.38:5000

# Отправляет образы в локальный репозиторий

docker tag marm-data-printform ${REGISTRY}/marm-data-printform
docker tag marm-yarg ${REGISTRY}/marm-yarg
docker tag marm-server-printform ${REGISTRY}/marm-server-printform

docker push ${REGISTRY}/marm-data-printform
docker push ${REGISTRY}/marm-yarg
docker push ${REGISTRY}/marm-server-printform