#!/usr/bin/env bash

[ -z $1 ] && echo "Please specify env" && exit 1

ENV=$1
LOG_OPTS="--log-driver=json-file --log-opt max-size=100m --log-opt max-file=3"

ssh ${ENV} ./pull-image-from-registry marm-router-shared

ssh ${ENV} docker rm -vf marm-router

ssh ${ENV} docker run -d --name marm-router \
    --net marm-router \
    -p 80:80 \
    ${LOG_OPTS} \
    marm-router-shared

