#!/bin/bash
set -e

if [ "$1" = 'mongod' ] && [ ! -f /data/db/admin.ns ]; then
    mongod --fork --logpath /var/log/mongodb.log --smallfiles
    sleep 10
    mongo admin /tmp/create-user.js
    kill $(pgrep mongo)
    sleep 5
fi

exec "$@"