#!/usr/bin/env bash

[ -z $1 ] && echo "Please specify project name" && exit 1
[ -z $2 ] && echo "Please specify box version" && exit 1
[ -z $3 ] && echo "Please specify build number" && exit 1
[ -z $4 ] && echo "Please specify branch name" && exit 1

PROJECT=$1
VERSION=$2
BUILD=$3
BRANCH=$4

FULL_VERSION=${VERSION}.${BUILD}
RELEASE_PATH=/var/www/releases/${PROJECT}/${FULL_VERSION}

set -e

mkdir -p ${RELEASE_PATH}
cd ${RELEASE_PATH}

git clone ssh://git@party.altarix.ru:2222/box.git
git clone ssh://git@party.altarix.ru:2222/integrator.git

cd ${RELEASE_PATH}/box && git checkout ${BRANCH}
cd ${RELEASE_PATH}/integrator && git checkout ${BRANCH}

sudo chmod 777 -R ${RELEASE_PATH}/box/protected/runtime
sudo chmod 777 -R ${RELEASE_PATH}/integrator/protected/runtime

docker run --rm --volume ${RELEASE_PATH}/box:/var/www marm-app /bin/bash -c 'cd /var/www/protected && composer install'
docker run --rm --volume ${RELEASE_PATH}/integrator:/var/www marm-app /bin/bash -c 'cd /var/www/protected && composer install'