#!/usr/bin/env bash

# Образы для разворачивания проекта

[ -z $1 ] && echo "Please specify project name" && exit 1

PROJECT=$1

REGISTRY=172.29.134.38:5000

docker pull ${REGISTRY}/marm-data-log-${PROJECT}
docker pull ${REGISTRY}/marm-cron-${PROJECT}
docker pull ${REGISTRY}/marm-logrotate-${PROJECT}

docker tag ${REGISTRY}/marm-data-log-${PROJECT} marm-data-log-${PROJECT}
docker tag ${REGISTRY}/marm-cron-${PROJECT} marm-cron-${PROJECT}
docker tag ${REGISTRY}/marm-logrotate-${PROJECT} marm-logrotate-${PROJECT}

