#!/usr/bin/env bash

# Образы для разворачивания сервиса печатных форм

REGISTRY=172.29.134.38:5000

docker pull ${REGISTRY}/marm-data-printform
docker pull ${REGISTRY}/marm-server-printform
docker pull ${REGISTRY}/marm-yarg


docker tag ${REGISTRY}/marm-data-printform marm-data-printform
docker tag ${REGISTRY}/marm-server-printform marm-server-printform
docker tag ${REGISTRY}/marm-yarg marm-yarg

