#!/usr/bin/env bash

[ -z $1 ] && echo "Please specify project name" && exit 1
[ -z $2 ] && echo "Please specify box version" && exit 1
[ -z $3 ] && echo "Please specify build number" && exit 1

PROJECT=$1
VERSION=$2
BUILD=$3

FULL_VERSION=${VERSION}.${BUILD}
FULL_NAME=${PROJECT}-${FULL_VERSION}
NETWORK=marm-${FULL_NAME}

# data (code, logs ...)

docker rm -v marm-data-box-${FULL_NAME}
docker rm -v marm-data-integrator-${FULL_NAME}
docker rm -v marm-data-cms-${FULL_NAME}
docker rm -v marm-data-log-${FULL_NAME}

# php (box, integrator)

docker rm -vf marm-app-box-${FULL_NAME}
docker rm -vf marm-app-integrator-${FULL_NAME}
docker rm -vf marm-app-cms-${FULL_NAME}

# servers (box, integrator)

docker rm -vf marm-server-box-${FULL_NAME}
docker rm -vf marm-server-integrator-${FULL_NAME}
docker rm -vf marm-server-cms-${FULL_NAME}

# cron

docker rm -vf marm-cron-${FULL_NAME}

# logrotate

# project logs
docker rm -vf marm-logrotate-${FULL_NAME}

# php
docker rm -vf marm-logrotate-app-box-${FULL_NAME}
docker rm -vf marm-logrotate-app-integrator-${FULL_NAME}
docker rm -vf marm-logrotate-app-cms-${FULL_NAME}

# server box
docker rm -vf marm-logrotate-server-box-${FULL_NAME}
docker rm -vf marm-logrotate-server-integrator-${FULL_NAME}
docker rm -vf marm-logrotate-server-cms-${FULL_NAME}

# remove network
docker network rm ${NETWORK}