#!/usr/bin/env bash

PROJECT="mgsn"
VERSION="2.4.12"
BUILD=1

FULL_VERSION=${VERSION}.${BUILD}
FULL_NAME=${PROJECT}-${FULL_VERSION}
NETWORK=marm-${FULL_NAME}

docker network disconnect marm-router marm-server-integrator-${FULL_NAME}

remove-build ${PROJECT} ${VERSION} ${BUILD}

echo -e "\nREMOVED BUILD INFO:\n"
echo -e "project: ${PROJECT}"
echo -e "version: ${VERSION}"
echo -e "build: ${BUILD}"
echo -e "network: ${NETWORK}\n"

echo -e "disconnect marm-server-integrator-${FULL_NAME} from marm-router\n"