#!/usr/bin/env bash

PROJECT="nadzor"
VERSION="2.4.12"
BUILD=1
BOX_PORT=8081
CMS_PORT=8801

FULL_VERSION=${VERSION}.${BUILD}
FULL_NAME=${PROJECT}-${FULL_VERSION}
NETWORK=marm-${FULL_NAME}

./run-build ${PROJECT} ${VERSION} ${BUILD} ${BOX_PORT} ${CMS_PORT}

# скачиваем wsdl
docker exec marm-cron-nadzor-2.4.12.1 /bin/bash -c 'curl http://77.247.243.35:1024/nadzor_service/NadzorService.asmx?WSDL -o /var/www/integrator/protected/runtime/nadzor.wsdl &> /var/log/marm/nadzor/cron/wsdl.log && cp /var/www/integrator/protected/runtime/nadzor.wsdl /var/www/box/protected/runtime/nadzor.wsdl'

# запуск миграций
docker exec marm-app-box-nadzor-2.4.12.1 /var/www/box/protected/yiic migrate --migrationPath=application.migrations.nadzor --connectionID=db_nadzor --interactive=0

docker network connect ${NETWORK} marm-server-printform

echo -e "\nBUILD INFO:\n"
echo -e "project: ${PROJECT}"
echo -e "version: ${VERSION}"
echo -e "build: ${BUILD}"
echo -e "box port: ${BOX_PORT}"
echo -e "cms port: ${CMS_PORT}"
echo -e "network: ${NETWORK}\n"
echo -e "Connect marm-server-printform with ${NETWORK} network\n"