#!/usr/bin/env bash

[ -z $1 ] && echo "Please specify project name" && exit 1

PROJECT=$1

LOG_OPTS="--log-driver=json-file --log-opt max-size=100m --log-opt max-file=3"

docker run -d --name marm-router \
    --net marm-router \
    -p 80:80 \
    ${LOG_OPTS} \
    marm-router-${PROJECT}