#!/usr/bin/env bash

[ -z $1 ] && echo "Please specify project name" && exit 1
[ -z $2 ] && echo "Please specify box version" && exit 1
[ -z $3 ] && echo "Please specify build number" && exit 1

PROJECT=$1
VERSION=$2
BUILD=$3

FULL_VERSION=${VERSION}.${BUILD}
FULL_NAME=${PROJECT}-${FULL_VERSION}
NETWORK=marm-${FULL_NAME}

# php (box, integrator)

docker start marm-app-box-${FULL_NAME}
docker start marm-app-integrator-${FULL_NAME}

# servers (box, integrator)

docker start marm-server-box-${FULL_NAME}
docker start marm-server-integrator-${FULL_NAME}

# cron

docker start marm-cron-${FULL_NAME}

## logrotate

# project logs
docker start marm-logrotate-${FULL_NAME}

# php
docker start marm-logrotate-app-box-${FULL_NAME}
docker start marm-logrotate-app-integrator-${FULL_NAME}

# server
docker start marm-logrotate-server-box-${FULL_NAME}
docker start marm-logrotate-server-integrator-${FULL_NAME}

# router
docker start marm-router


